project:
  type: website
  output-dir: "docs"

website:
  title: "WSPHA Disease Control - PHQ"
  # image: "wspha_logo1.png"
  cookie-consent:
    type: express
    style: headline
    palette: dark
    prefs-text: "Cookies"
    
  google-analytics: 
    tracking-id: "G-xxxxxxx"
    anonymize-ip: true
    
  announcement: 
    icon: info-square
    dismissable: true
    content: "**Take note** - this website is still under construction"
    type: info
    position: below-navbar
    
  sidebar:
    title: "My Portfolio"
    style: "floating"     # or "docked" or "overlay"
    search: true          # optional search box
    contents:
      - href: index.qmd
        text: Home
      # - href: portfolio.qmd
      #   text: Portfolio
      - section: Surveillance & Outbreaks
        contents:
          - href: posts/outbreak-report/index.qmd
            text: Outbreak Reports
          - href: posts/weekly-syndromic-reports/index.qmd
            text: Syndromic Surveillance
          - href: posts/skin-ntds-reports/index.qmd
            text: Neglected Tropica Diseases
      - section: Disease Control Programs
        contents:
          - href: disease_control_programs/tuberculosis/index.qmd
            text: Tuberculosis Updates
          - href: disease_control_programs/malaria/index.qmd
            text: Malaria Updates
          - href: disease_control_programs/hiv_sti/index.qmd
            text: HIV & Program Updates
          - href: disease_control_programs/non_communicable_diseases/index.qmd
            text: NCDs Updates
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        menu: 
          - text: "Weekly Syndromic Surveillance Reports"
            file: posts/weekly-syndromic-reports/index.qmd
          - text: "Weekly Skin NTDs Reports"
            file: posts/skin-ntds-reports/index.qmd
          - text: "Outbreak Reports"
            file: posts/outbreak-report/index.qmd
        # file: portfolio.qmd
      - text: "Disease Control Programs"
        menu:
          - text: "Quarterly Tuberculosis Reports, Feedback"
            file: disease_control_programs/tuberculosis/index.qmd
          - text: "Quarterly Malaria Reports, Feedback"
            file: disease_control_programs/malaria/index.qmd
          - text: "Monthly HIV/STI Reports Feedback"
            file: disease_control_programs/hiv_sti/index.qmd
          - text: "Quarterly NCDs Report Feedbacks"
            file: disease_control_programs/non_communicable_diseases/index.qmd
      - text: "Authors' Bio & CV"
        file: CV.qmd
      
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/raphael-anea-783739113
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=100086260155966
      - icon: envelope
        href: ryilan.anea01@gmail.com
      - icon: github
        menu: 
          - text: Source Code
            href: https://github.com/RaphAneaYilan/MyBlog/blob/main/index.qmd
          - text: Report a Bug
            href: https://github.com/RaphAneaYilan/MyBlog/issues
            
  page-footer:
    left: "Raphael Yilan ANEA &copy; <script>document.write(new Date().getFullYear())</script>"
    # center: "Build on [Quarto Academic Website Template](https://github.com/drganghe/quarto-academic-website-template)"
    # right:
    #   - icon: github
    #     href: https://github.com/dcosme
    #     target: _blank
    #   - text: "{{< fa brands bluesky >}}"
    #     href: https://bsky.app/profile/dcosme.bsky.social
    #     target: _blank
    #   # - icon: rss
      #   href: posts.xml
      #   target: _blank

  search:
    location: navbar
    type: textbox

  reader-mode: true

  draft-mode: unlinked

  # repo-url: https://github.com/dcosme/dcosme.github.io
#  repo-actions: [edit, issue, source]

  open-graph: true

  twitter-card: false
#  card-style: summary

  # site-url: "https://dcosme.github.io"

  google-analytics:
    tracking-id: "G-6N7PZ01PG8"  # Please delete or replace with your own tracking ID
    anonymize-ip: true

# bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

   
format:
  html:
    theme:
      - sandstone
      - brand
    css: bootstrap-sandstone.css
    head-content: |
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    self-contained: true
    embed-resources: true
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/dcosme\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"
    
    
title-block-banner: "background-images.jpeg"
title-block-style: manuscript
 
editor: visual

