project:
  type: website
  output-dir: "docs"

website:
  title: "WSPHA Disease Control - PHQ"
  # image: "wspha_logo1.png"
  cookie-consent:
    type: express
    style: headline
    palette: dark
    prefs-text: "Cookies"
    
  google-analytics: 
    tracking-id: "G-xxxxxxx"
    anonymize-ip: true
    
  announcement: 
    icon: info-square
    dismissable: true
    content: "**Take note** - this website is still under construction"
    type: info
    position: below-navbar
    
  sidebar:
    title: "My Portfolio"
    style: "floating"     # or "docked" or "overlay"
    search: true          # optional search box
    contents:
      - href: index.qmd
        text: Home
      # - href: portfolio.qmd
      #   text: Portfolio
      - section: Surveillance & Outbreaks
        contents:
          - href: posts/outbreak-report/index.qmd
            text: Outbreak Reports
          - href: posts/post-with-code/index.qmd
            text: Syndromic Surveillance
          - href: posts/skin-ntds-reports/index.qmd
            text: Neglected Tropica Diseases
      - section: Disease Control Programs
        contents:
          - href: disease_control_programs/tuberculosis/index.qmd
            text: Tuberculosis Updates
          - href: disease_control_programs/malaria/index.qmd
            text: Malaria Updates
          - href: disease_control_programs/hiv_sti/index.qmd
            text: HIV & Program Updates
          - href: disease_control_programs/non_communicable_diseases/index.qmd
            text: NCDs Updates
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        menu: 
          - text: "Weekly Syndromic Surveillance Reports"
            file: posts/weekly-syndromic-reports/index.qmd
          - text: "Weekly Skin NTDs Reports"
            file: posts/skin-ntds-reports/index.qmd
          - text: "Outbreak Reports"
            file: posts/outbreak-report/index.qmd
        # file: portfolio.qmd
      - text: "Disease Control Programs"
        menu:
          - text: "Quarterly Tuberculosis Reports, Feedback"
            file: disease_control_programs/tuberculosis/index.qmd
          - text: "Quarterly Malaria Reports, Feedback"
            file: disease_control_programs/malaria/index.qmd
          - text: "Monthly HIV/STI Reports Feedback"
            file: disease_control_programs/hiv_sti/index.qmd
          - text: "Quarterly NCDs Report Feedbacks"
            file: disease_control_programs/non_communicable_diseases/index.qmd
      - text: "Authors' Bio & CV"
        file: CV.qmd
      
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/raphael-anea-783739113
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=100086260155966
      - icon: envelope
        href: ryilan.anea01@gmail.com
      - icon: github
        menu: 
          - text: Source Code
            href: https://github.com/RaphAneaYilan/MyBlog/blob/main/index.qmd
          - text: Report a Bug
            href: https://github.com/RaphAneaYilan/MyBlog/issues
format:
  html:
    theme:
      - sandstone
      - brand
    css: bootstrap-sandstone.css
    head-content: |
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    self-contained: true
    embed-resources: true
title-block-banner: "background-images.jpeg"
title-block-style: manuscript
 
editor: visual

