project:
  type: website
  output-dir: "docs"

website:
  title: "Raphael Yilan Anea"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "My CV"
        file: CV.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/raphael-anea-783739113
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=100086260155966
      - icon: envelope
        href: ryilan.anea01@gmail.com
      - icon: github
        href: https://github.com/RaphAneaYilan
format:
  html:
    theme:
      - slate
      - brand
    css: styles.css
    self-contained: true
    embed-resources: true

editor: visual

