project:
  type: website
  output-dir: "docs"

website:
  title: "My Personal Blog"
  sidebar:
    title: "My Portfolio"
    style: "floating"     # or "docked" or "overlay"
    search: true          # optional search box
    contents:
      - href: index.qmd
        text: Home
      # - href: portfolio.qmd
      #   text: Portfolio
      - section: Portfolio
        contents: 
          - href: posts/outbreak-report/index.qmd
            text: WSP Outbreak Reports
          - href: posts/post-with-code/index.qmd
            text: WSP Syndromic Surveillance Updates
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        # file: portfolio.qmd
        menu: 
          - text: "Welcome blog"
            file: posts/welcome/index.qmd
          - text: "Surveillance Report"
            file: posts/post-with-code/index.qmd
          - text: "Outbreak Reports"
            file: posts/outbreak-report/index.qmd
      - text: "My CV"
        file: CV.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/raphael-anea-783739113
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=100086260155966
      - icon: envelope
        href: ryilan.anea01@gmail.com
      - icon: github
        menu: 
          - text: Source Code
            href: https://github.com/RaphAneaYilan/MyBlog/blob/main/index.qmd
          - text: Report a Bug
            href: https://github.com/RaphAneaYilan/MyBlog/issues
format:
  html:
    theme:
      - sandstone
      - brand
    css: bootstrap-sandstone.css
    self-contained: true
    embed-resources: true

editor: visual

